// Icon field stores a react-icons component key resolved in iconMap.js
export const TOOLS = [
  { name:"AI Content Writer", slug:"ai-content-writer", category:"AI", icon:"FiEdit3", description:"Blogs, emails, product descriptions", badge:"ai", isAI:true },
  { name:"AI Summarizer", slug:"ai-summarizer", category:"AI", icon:"FiFileText", description:"Summarize any text instantly", badge:"ai", isAI:true },
  { name:"AI Grammar Checker", slug:"ai-grammar-checker", category:"AI", icon:"FiCheckCircle", description:"Fix grammar and improve writing", badge:"ai", isAI:true },
  { name:"AI Code Generator", slug:"ai-code-generator", category:"AI", icon:"FiCode", description:"Generate code from descriptions", badge:"ai", isAI:true },
  { name:"AI Translator", slug:"ai-translator", category:"AI", icon:"FiGlobe", description:"Translate to 50+ languages", badge:"ai", isAI:true },
  { name:"AI Resume Builder", slug:"ai-resume-builder", category:"AI", icon:"FiFileText", description:"ATS-friendly professional resumes", badge:"ai", isAI:true },
  { name:"AI Email Writer", slug:"ai-email-writer", category:"AI", icon:"FiMail", description:"Compose professional emails fast", badge:"ai", isAI:true },
  { name:"AI Blog Writer", slug:"ai-blog-writer", category:"AI", icon:"FiBookOpen", description:"SEO-optimized blog posts", badge:"ai", isAI:true },
  { name:"AI SEO Optimizer", slug:"ai-seo-optimizer", category:"AI", icon:"FiTrendingUp", description:"Optimize content for search", badge:"ai", isAI:true },
  { name:"AI Cover Letter", slug:"ai-cover-letter", category:"AI", icon:"FiClipboard", description:"Tailored cover letters", badge:"ai", isAI:true },
  { name:"AI Hashtag Generator", slug:"ai-hashtag-generator", category:"AI", icon:"FiHash", description:"Trending hashtags for any topic", badge:"ai", isAI:true },
  { name:"AI Prompt Generator", slug:"ai-prompt-generator", category:"AI", icon:"FiZap", description:"Better prompts for any AI", badge:"new", isAI:true },
  { name:"PDF Compressor", slug:"pdf-compressor", category:"PDF", icon:"FiPackage", description:"Reduce PDF size without quality loss" },
  { name:"Merge PDF", slug:"merge-pdf", category:"PDF", icon:"FiLink", description:"Combine multiple PDFs into one" },
  { name:"Split PDF", slug:"split-pdf", category:"PDF", icon:"FiScissors", description:"Split PDF into separate files" },
  { name:"PDF to Word", slug:"pdf-to-word", category:"PDF", icon:"FiFileText", description:"Convert PDF to editable Word", badge:"hot" },
  { name:"PDF to JPG", slug:"pdf-to-jpg", category:"PDF", icon:"FiImage", description:"Export PDF pages as images" },
  { name:"Protect PDF", slug:"protect-pdf", category:"PDF", icon:"FiLock", description:"Password-protect your PDF" },
  { name:"Image Compressor", slug:"image-compressor", category:"Image", icon:"FiImage", description:"Compress images up to 90%" },
  { name:"Background Remover", slug:"background-remover", category:"Image", icon:"FiScissors", description:"AI background removal", badge:"ai", isAI:true },
  { name:"Image Resizer", slug:"image-resizer", category:"Image", icon:"FiMaximize2", description:"Resize to exact dimensions" },
  { name:"OCR – Image to Text", slug:"ocr", category:"Image", icon:"FiSearch", description:"Extract text from any image", badge:"new" },
  { name:"JSON Formatter", slug:"json-formatter", category:"Developer", icon:"FiCode", description:"Format and validate JSON" },
  { name:"Base64 Encoder", slug:"base64-encoder", category:"Developer", icon:"FiHash", description:"Encode and decode base64" },
  { name:"JWT Decoder", slug:"jwt-decoder", category:"Developer", icon:"FiKey", description:"Inspect JWT tokens" },
  { name:"UUID Generator", slug:"uuid-generator", category:"Developer", icon:"FiHash", description:"Generate unique identifiers" },
  { name:"Regex Tester", slug:"regex-tester", category:"Developer", icon:"FiSearch", description:"Test regular expressions" },
  { name:"Markdown Editor", slug:"markdown-editor", category:"Developer", icon:"FiFileText", description:"Live Markdown preview", badge:"new" },
  { name:"Word Counter", slug:"word-counter", category:"Writing", icon:"FiHash", description:"Count words, chars, sentences" },
  { name:"Case Converter", slug:"case-converter", category:"Writing", icon:"FiType", description:"Convert text case instantly" },
  { name:"Text Compare", slug:"text-compare", category:"Writing", icon:"FiGitPullRequest", description:"Find differences between two texts" },
  { name:"Lorem Ipsum", slug:"lorem-ipsum", category:"Writing", icon:"FiFileText", description:"Generate placeholder lorem ipsum text" },
  { name:"Slug Generator", slug:"slug-generator", category:"Writing", icon:"FiLink", description:"Generate URL-friendly slugs from text" },
  { name:"Password Generator", slug:"password-generator", category:"Security", icon:"FiLock", description:"Strong passwords instantly" },
  { name:"Hash Generator", slug:"hash-generator", category:"Security", icon:"FiHash", description:"MD5, SHA1, SHA256 and more" },
  { name:"EMI Calculator", slug:"emi-calculator", category:"Finance", icon:"FiPercent", description:"Calculate loan EMI and interest" },
  { name:"Currency Converter", slug:"currency-converter", category:"Finance", icon:"FiRefreshCw", description:"Live exchange rates", badge:"new" },
  { name:"QR Generator", slug:"qr-generator", category:"Developer", icon:"FiGrid", description:"Generate QR codes" },
  { name:"Invoice Generator", slug:"invoice-generator", category:"Business", icon:"FiFileText", description:"Professional invoices as PDF" },
  { name:"GPA Calculator", slug:"gpa-calculator", category:"Education", icon:"FiAward", description:"Calculate GPA from grades" },
  { name:"Keyword Generator", slug:"keyword-generator", category:"SEO", icon:"FiTag", description:"High-value keywords for any niche", isAI:true, badge:"ai" },
  { name:"Meta Tag Generator", slug:"meta-tag-generator", category:"SEO", icon:"FiCode", description:"Generate perfect meta tags" },
];

export const CATEGORIES = [
  { name:"AI", icon:"FiZap", color:"#7F77DD" },
  { name:"PDF", icon:"FiFileText", color:"#E24B4A" },
  { name:"Image", icon:"FiImage", color:"#1D9E75" },
  { name:"Video", icon:"FiVideo", color:"#BA7517" },
  { name:"Audio", icon:"FiMusic", color:"#D4537E" },
  { name:"SEO", icon:"FiTrendingUp", color:"#378ADD" },
  { name:"Developer", icon:"FiCode", color:"#534AB7" },
  { name:"Writing", icon:"FiEdit3", color:"#639922" },
  { name:"Finance", icon:"FiDollarSign", color:"#0F6E56" },
  { name:"Security", icon:"FiLock", color:"#993556" },
  { name:"Business", icon:"FiBriefcase", color:"#BA7517" },
  { name:"Education", icon:"FiAward", color:"#378ADD" },
];
